//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibiaPixelBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TibiaPixelBot.ResourceLanguage", typeof(ResourceLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Bleeding disabled!.
        /// </summary>
        internal static string AutoCureBleedingDisabled {
            get {
                return ResourceManager.GetString("AutoCureBleedingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Bleeding enabled!.
        /// </summary>
        internal static string AutoCureBleedingEnabled {
            get {
                return ResourceManager.GetString("AutoCureBleedingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Burning disabled!.
        /// </summary>
        internal static string AutoCureBurningDisabled {
            get {
                return ResourceManager.GetString("AutoCureBurningDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Burning enabled!.
        /// </summary>
        internal static string AutoCureBurningEnabled {
            get {
                return ResourceManager.GetString("AutoCureBurningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Curse disabled!.
        /// </summary>
        internal static string AutoCureCurseDisabled {
            get {
                return ResourceManager.GetString("AutoCureCurseDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Curse enabled!.
        /// </summary>
        internal static string AutoCureCurseEnabled {
            get {
                return ResourceManager.GetString("AutoCureCurseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Electrification disabled!.
        /// </summary>
        internal static string AutoCureElectrificationDisabled {
            get {
                return ResourceManager.GetString("AutoCureElectrificationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Electrification enabled!.
        /// </summary>
        internal static string AutoCureElectrificationEnabled {
            get {
                return ResourceManager.GetString("AutoCureElectrificationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Poison disabled!.
        /// </summary>
        internal static string AutoCurePoisonDisabled {
            get {
                return ResourceManager.GetString("AutoCurePoisonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cure Poison enabled!.
        /// </summary>
        internal static string AutoCurePoisonEnabled {
            get {
                return ResourceManager.GetString("AutoCurePoisonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Eat disabled!.
        /// </summary>
        internal static string AutoFoodDisabled {
            get {
                return ResourceManager.GetString("AutoFoodDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Eat enabled!.
        /// </summary>
        internal static string AutoFoodEnabled {
            get {
                return ResourceManager.GetString("AutoFoodEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Haste disabled!.
        /// </summary>
        internal static string AutoHasteDisabled {
            get {
                return ResourceManager.GetString("AutoHasteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Haste enabled!.
        /// </summary>
        internal static string AutoHasteEnabled {
            get {
                return ResourceManager.GetString("AutoHasteEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mana Shield disabled!.
        /// </summary>
        internal static string AutoManaShieldDisabled {
            get {
                return ResourceManager.GetString("AutoManaShieldDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mana Shield enabled!.
        /// </summary>
        internal static string AutoManaShieldEnabled {
            get {
                return ResourceManager.GetString("AutoManaShieldEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Remove Paralize disabled!.
        /// </summary>
        internal static string AutoParalizeDisabled {
            get {
                return ResourceManager.GetString("AutoParalizeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Remove Paralize enabled!.
        /// </summary>
        internal static string AutoParalizeEnabled {
            get {
                return ResourceManager.GetString("AutoParalizeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan could not be used!.
        /// </summary>
        internal static string AutoScanCould {
            get {
                return ResourceManager.GetString("AutoScanCould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan disabled!.
        /// </summary>
        internal static string AutoScanDisabled {
            get {
                return ResourceManager.GetString("AutoScanDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan enabled!.
        /// </summary>
        internal static string AutoScanEnabled {
            get {
                return ResourceManager.GetString("AutoScanEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can not export configuration....
        /// </summary>
        internal static string CantExport {
            get {
                return ResourceManager.GetString("CantExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture the image on the main monitor or try another one..
        /// </summary>
        internal static string CaptureImage {
            get {
                return ResourceManager.GetString("CaptureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned Logs!.
        /// </summary>
        internal static string CleanedLogs {
            get {
                return ResourceManager.GetString("CleanedLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can not read file....
        /// </summary>
        internal static string ErroReadFile {
            get {
                return ResourceManager.GetString("ErroReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Loading Resources..
        /// </summary>
        internal static string ErrorLoadingResources {
            get {
                return ResourceManager.GetString("ErrorLoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string FormSettingsName {
            get {
                return ResourceManager.GetString("FormSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIXEL - STOP!.
        /// </summary>
        internal static string FormStop {
            get {
                return ResourceManager.GetString("FormStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIXEL - WORKING!.
        /// </summary>
        internal static string FormWorking {
            get {
                return ResourceManager.GetString("FormWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing successfully!.
        /// </summary>
        internal static string ImportSucces {
            get {
                return ResourceManager.GetString("ImportSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is with negative numbers..
        /// </summary>
        internal static string LocationNegativeNum {
            get {
                return ResourceManager.GetString("LocationNegativeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For safety reasons the function was stopped by continuous repetitions!.
        /// </summary>
        internal static string MotivoSeguranca {
            get {
                return ResourceManager.GetString("MotivoSeguranca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Capturing position....
        /// </summary>
        internal static string NotCapturing {
            get {
                return ResourceManager.GetString("NotCapturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tibia Pixel Bot file.
        /// </summary>
        internal static string OpenTPB {
            get {
                return ResourceManager.GetString("OpenTPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position saved successfully!.
        /// </summary>
        internal static string PositionSaved {
            get {
                return ResourceManager.GetString("PositionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        internal static string SavedSucces {
            get {
                return ResourceManager.GetString("SavedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tibia Pixel Bot file.
        /// </summary>
        internal static string SaveTPB {
            get {
                return ResourceManager.GetString("SaveTPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPELL:.
        /// </summary>
        internal static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting auto actions....
        /// </summary>
        internal static string StartingAutoAction {
            get {
                return ResourceManager.GetString("StartingAutoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoped all!.
        /// </summary>
        internal static string StopAll {
            get {
                return ResourceManager.GetString("StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia is not open..
        /// </summary>
        internal static string TibiaNotOpen {
            get {
                return ResourceManager.GetString("TibiaNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos do Tibia Pixel Bot.
        /// </summary>
        internal static string TPBFiles {
            get {
                return ResourceManager.GetString("TPBFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some value entered incorrectly or out of standards!.
        /// </summary>
        internal static string ValueIncorrectly {
            get {
                return ResourceManager.GetString("ValueIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification added!.
        /// </summary>
        internal static string VerificationAdded {
            get {
                return ResourceManager.GetString("VerificationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification altered!.
        /// </summary>
        internal static string VerificationAltered {
            get {
                return ResourceManager.GetString("VerificationAltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification excluded!.
        /// </summary>
        internal static string VerificationExcluded {
            get {
                return ResourceManager.GetString("VerificationExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification stopped!.
        /// </summary>
        internal static string VerificationStopped {
            get {
                return ResourceManager.GetString("VerificationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to capture!.
        /// </summary>
        internal static string WaitingCapture {
            get {
                return ResourceManager.GetString("WaitingCapture", resourceCulture);
            }
        }
    }
}
